apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bluesky-firehose-data
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi 
