name: DockerImage

on:
  push:
    branches:
      - main

jobs:
  deploy-poc:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: harbor.allocsoc.net
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build, tag, and push image to Harbor
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: harbor.allocsoc.net/bluesky/poc:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 
  update-manifests:
    needs: deploy-poc
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update image in deployment
        run: |
          # Update the image tag in deployment.yaml
          NEW_IMAGE=harbor.allocsoc.net/bluesky/poc:${{ github.sha }}
          sed -i "s|image: .*|image: ${NEW_IMAGE}|" k8s/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add k8s/deployment.yaml
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update image to ${{ github.sha }}"
            git push
          fi
